Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/a_of_time.h File Reference
a_of_time.h File Reference
Functions
double a_of_supercom_time (struct params *par, struct units *unit, double tau)
double time_of_a_supercom (struct params *par, struct units *unit, double a_init)
void test_a_of_time (struct params *par, struct units *unit)
Function Documentation
a_of_supercom_time()
double a_of_supercom_time (struct params * par, struct units * unit, double tau)
References a_dot_supercom_for_rk(), units::H0, jac_a_dot_supercom_for_rk(), mu(), params::omegal, and params::omegam.
Referenced by test_a_of_time().
time_of_a_supercom()
double time_of_a_supercom (struct params * par, struct units * unit, double a_init)
References a_dot_supercom_for_rk(), units::H0, jac_a_dot_supercom_for_rk(), mu(), params::omegal, and params::omegam.
test_a_of_time()
void test_a_of_time (struct params * par, struct units * unit)
References a_of_supercom_time().