Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/a_of_time.c File Reference
a_of_time.c File Reference
Macros
#define pow2(x) ((x)*(x))
#define pow3(x) ((x)*(x)*(x))
#define pow4(x) ((x)*(x)*(x)*(x))
Functions
int a_dot_supercom_for_rk (double t, const double y[], double f[], void *params)
int jac_a_dot_supercom_for_rk (double t, const double y[], double *dfdy, double dfdt[], void *params)
double a_of_supercom_time (struct params *par, struct units *unit, double tau)
double time_of_a_supercom (struct params *par, struct units *unit, double a_init)
void test_a_of_time (struct params *par, struct units *unit)
Macro Definition Documentation
pow2
#define pow2 (x) ((x)*(x))
pow3
#define pow3 (x) ((x)*(x)*(x))
pow4
#define pow4 (x) ((x)*(x)*(x)*(x))
Function Documentation
a_dot_supercom_for_rk()
int a_dot_supercom_for_rk (double t, const double y[], double f[], void * params)
References mu(), and pow3.
Referenced by a_of_supercom_time(), and time_of_a_supercom().
jac_a_dot_supercom_for_rk()
int jac_a_dot_supercom_for_rk (double t, const double y[], double * dfdy, double dfdt[], void * params)
References mu(), and pow3.
Referenced by a_of_supercom_time(), and time_of_a_supercom().
a_of_supercom_time()
double a_of_supercom_time (struct params * par, struct units * unit, double tau)
References a_dot_supercom_for_rk(), units::H0, jac_a_dot_supercom_for_rk(), mu(), params::omegal, and params::omegam.
Referenced by test_a_of_time().
time_of_a_supercom()
double time_of_a_supercom (struct params * par, struct units * unit, double a_init)
References a_dot_supercom_for_rk(), units::H0, jac_a_dot_supercom_for_rk(), mu(), params::omegal, and params::omegam.
test_a_of_time()
void test_a_of_time (struct params * par, struct units * unit)
References a_of_supercom_time().