Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/allocator.h File Reference
allocator.h File Reference
Functions
void alloc_int_2 (int ***a, int d1, int d2)
void alloc_int_3 (int ****a, int d1, int d2, int d3)
void alloc_int_4 (int *****a, int d1, int d2, int d3, int d4)
void alloc_float_2 (float ***a, int d1, int d2)
void alloc_float_3 (float ****a, int d1, int d2, int d3)
void alloc_float_4 (float *****a, int d1, int d2, int d3, int d4)
void alloc_double_2 (double ***a, int d1, int d2)
void alloc_double_3 (double ****a, int d1, int d2, int d3)
void alloc_double_4 (double *****a, int d1, int d2, int d3, int d4)
void alloc_long_2 (long ***a, int d1, int d2)
void alloc_long_3 (long ****a, int d1, int d2, int d3)
void alloc_long_4 (long *****a, int d1, int d2, int d3, int d4)
void alloc_char_2 (char ***a, int d1, int d2)
void alloc_char_3 (char ****a, int d1, int d2, int d3)
void alloc_char_4 (char *****a, int d1, int d2, int d3, int d4)
Function Documentation
alloc_int_2()
void alloc_int_2 (int *** a, int d1, int d2)
alloc_int_3()
void alloc_int_3 (int **** a, int d1, int d2, int d3)
alloc_int_4()
void alloc_int_4 (int ***** a, int d1, int d2, int d3, int d4)
alloc_float_2()
void alloc_float_2 (float *** a, int d1, int d2)
alloc_float_3()
void alloc_float_3 (float **** a, int d1, int d2, int d3)
alloc_float_4()
void alloc_float_4 (float ***** a, int d1, int d2, int d3, int d4)
alloc_double_2()
void alloc_double_2 (double *** a, int d1, int d2)
alloc_double_3()
void alloc_double_3 (double **** a, int d1, int d2, int d3)
Referenced by allocate_grids_mm(), init_grid(), solve_poisson_fftw(), and solve_spherical_mond().
alloc_double_4()
void alloc_double_4 (double ***** a, int d1, int d2, int d3, int d4)
alloc_long_2()
void alloc_long_2 (long *** a, int d1, int d2)
alloc_long_3()
void alloc_long_3 (long **** a, int d1, int d2, int d3)
alloc_long_4()
void alloc_long_4 (long ***** a, int d1, int d2, int d3, int d4)
alloc_char_2()
void alloc_char_2 (char *** a, int d1, int d2)
alloc_char_3()
void alloc_char_3 (char **** a, int d1, int d2, int d3)
alloc_char_4()
void alloc_char_4 (char ***** a, int d1, int d2, int d3, int d4)