Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/cosmology.c File Reference
cosmology.c File Reference
Data Structures
struct params_int
Functions
double hubble (struct params *par, struct units *unit, double a)
double hubble2 (struct params *par, struct units *unit, double a)
double hubble_dot (struct params *par, struct units *unit, double a)
double a_dot (struct params *par, struct units *unit, double a)
double F (struct params *par, struct units *unit, double a)
double A (struct params *par, struct units *unit, double a)
double integrate_time_of_a (struct params *par, double a)
double integrand_time (double a, void *parameters)
void tabulate_t_of_a (struct params *par)
double a_of_t (struct params *par, double t)
Function Documentation
hubble()
double hubble (struct params * par, struct units * unit, double a)
References params::a, units::H0, params::omegal, params::omegam, and pow3.
hubble2()
double hubble2 (struct params * par, struct units * unit, double a)
References params::a, units::H0, params::omegal, params::omegam, pow2, and pow3.
hubble_dot()
double hubble_dot (struct params * par, struct units * unit, double a)
References params::a, units::H0, params::omegam, pow2, and pow3.
a_dot()
double a_dot (struct params * par, struct units * unit, double a)
References params::a, units::H0, params::omegal, params::omegam, and pow2.
F()
double F (struct params * par, struct units * unit, double a)
References params::a, params::omegal, params::omegam, and pow3.
A()
double A (struct params * par, struct units * unit, double a)
References params::a, params::omegal, params::omegam, and pow3.
integrate_time_of_a()
double integrate_time_of_a (struct params * par, double a)
References params::H0, integrand_time(), and params_int::par.
Referenced by leap_frog_variable(), and tabulate_t_of_a().
integrand_time()
double integrand_time (double a, void * parameters)
References params::omegal, params::omegam, pow2, and pow3.
Referenced by integrate_time_of_a().
tabulate_t_of_a()
void tabulate_t_of_a (struct params * par)
References integrate_time_of_a(), params_int::par, and params::t_of_a.
Referenced by init_physics().
a_of_t()
double a_of_t (struct params * par, double t)
References params_int::par, and params::t_of_a.
Referenced by get_gravity(), and leap_frog_variable().