Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/cycles_mm.c File Reference
cycles_mm.c File Reference
Functions
void do_one_v_cycle (struct grids_gravity_mm *gg, double a)
void cycle_v_mm_recursive (struct grids_gravity_mm *gg, double a)
void verbose_fine (struct grids_gravity_mm *gg, double a, int write_pot)
int cycle_v_mm (struct grids_gravity_mm *gg, double a)
Function Documentation
do_one_v_cycle()
void do_one_v_cycle (struct grids_gravity_mm * gg, double a)
Here is the V cycle of multigrid iterations.
Since our first grid is number zero, we go to coarse grids by going up, so the cycle is inverted.
Converge criteria:
See box in page 157 of Trottenberg, Oosterlee, Schuller, "Multigrid" for details.
The convergence criteria are based on the mean value of the residual
What we mean by "mean value" is defined in grid/get_mean_max_two_fields.
We have three criteria:
Absolute value of the residual (which has units, so it is not good).
Ratio of residual of latest step and first step. This is the one implemented in Ramses. It depends on how good or bad the initial guess is, so it makes no sence.
Comparison with truncation error.
< Number of Gauss-Seidel iterations per level.
< Number of Gauss-Seidel iterations per level.
< default=1. If 0 then solver does not go up in the first multigrid level (i.e. one grid scheme).
< default=1. If 0 then solver does not go up in the second multigrid level (i.e. two grids scheme).
< Number of Gauss-Seidel iterations per level.
References do_one_v_cycle(), grids_gravity_mm::g, go_down_mm(), GO_UP_FIRST, go_up_mm(), GO_UP_SECOND, gs_mm(), NGS, grids_gravity_mm::num_grids, grids_gravity_mm::par, grids_gravity_mm::verbose, and verbose_fine().
Referenced by cycle_v_mm(), and do_one_v_cycle().
cycle_v_mm_recursive()
void cycle_v_mm_recursive (struct grids_gravity_mm * gg, double a)
verbose_fine()
void verbose_fine (struct grids_gravity_mm * gg, double a, int write_pot)
References grids_gravity_mm::g, get_mean_max_two_fields(), grids_gravity_mm::n, grids_gravity_mm::res_chi, grids_gravity_mm::res_phi, residual_mm(), and grids_gravity_mm::verbose_coarse.
Referenced by cycle_v_mm(), and do_one_v_cycle().
cycle_v_mm()
int cycle_v_mm (struct grids_gravity_mm * gg, double a)
< Number of Gauss-Seidel iterations per level.
< Maximun number of complete V cycles before accepting that the solver will not converge.
References do_one_v_cycle(), grids_gravity_mm::g, get_mean_max_two_fields(), MAX_ITERATION, grids_gravity_mm::n, NGS, grids_gravity_mm::par, grids_gravity_mm::res_chi, grids_gravity_mm::res_phi, residual_mm(), grids_gravity_mm::trunc_chi, trunc_err_mm(), grids_gravity_mm::trunc_phi, and verbose_fine().
Referenced by solve_multigrid_mm().