Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/cycles_mm.h File Reference
cycles_mm.h File Reference
Functions
int cycle_v_mm (struct grids_gravity_mm *gg, double a)
Function Documentation
cycle_v_mm()
int cycle_v_mm (struct grids_gravity_mm * gg, double a)
< Number of Gauss-Seidel iterations per level.
< Maximun number of complete V cycles before accepting that the solver will not converge.
References do_one_v_cycle(), grids_gravity_mm::g, get_mean_max_two_fields(), MAX_ITERATION, grids_gravity_mm::n, NGS, grids_gravity_mm::par, grids_gravity_mm::res_chi, grids_gravity_mm::res_phi, residual_mm(), grids_gravity_mm::trunc_chi, trunc_err_mm(), grids_gravity_mm::trunc_phi, and verbose_fine().
Referenced by solve_multigrid_mm().