Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/differential_operators_mm.h File Reference
differential_operators_mm.h File Reference
Functions
void L_mm (double ***phi, double ***chi, double aa0, double M2, double h, double fourh, int i, int j, int k, int ip1, int im1, int jp1, int jm1, int kp1, int km1, double *operator_phi, double *operator_chi)
double mu (double x)
void evaluate_differential_operator_mm (struct grids_gravity_mm *gg, int grid, double ***phi, double ***chi, double ***operator_phi, double ***operator_chi)
Function Documentation
L_mm()
void L_mm (double *** phi, double *** chi, double aa0, double a2M2, double h, double fourh, int i, int j, int k, int ip1, int im1, int jp1, int jm1, int kp1, int km1, double * operator_phi, double * operator_chi)
Evaluates differential operators on a node
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
< For evaluating the MOND operator.
References dist(), MINUS, mu(), PLUS, pow2, X, Y, and Z.
Referenced by evaluate_differential_operator_mm(), residual_mm(), and trunc_err_mm().
mu()
double mu (double x)
Definition of the differential operator for both equations (Poisson like and MOND like).
Referenced by a_dot_supercom_for_rk(), a_of_supercom_time(), gs_node_mm(), jac_a_dot_supercom_for_rk(), L_mm(), and time_of_a_supercom().
evaluate_differential_operator_mm()
void evaluate_differential_operator_mm (struct grids_gravity_mm * gg, int grid, double *** phi, double *** chi, double *** operator_phi, double *** operator_chi)
Evaluates differential operators on the grid given by the second argument. Note that the grid does not have to necessarily be the grid gg->g. we do not store the result in the correponding variables in gg (instead we store it in the arguments res_phi, res_chi). This is in case you wat to store it somewhere else.
References grids_gravity_mm::a2M2, grids_gravity_mm::aa0, grids_gravity_mm::h, L_mm(), and grids_gravity_mm::n.
Referenced by go_up_mm().