Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/go_up_and_down_mm.h File Reference
go_up_and_down_mm.h File Reference
Functions
void go_up_mm (struct params *par, struct grids_gravity_mm *gg, double a)
void go_down_mm (struct grids_gravity_mm *gg, double a)
Function Documentation
go_up_mm()
void go_up_mm (struct params * par, struct grids_gravity_mm * gg, double a)
Two routines for going to coarse (up) and fine (down) grids. Moves everything to the next coarser grid.
Calculates source in coarse grid.
Transfer density and solution. See box in Trottenberg, pag 157.
The source is calculated with: S = operator(R(phi), R(rho), R(S)) - R(residual(phi, rho, S))
For first term:
Restrict three fields (including the source in this level, which is zero in the fine grid).
Evaluate operator. For the second term:
Calculate the residual in the level where we are.
Restrict that residual.
References grids_gravity_mm::chi, evaluate_differential_operator_mm(), grids_gravity_mm::g, grids_gravity_mm::n, grids_gravity_mm::par, grids_gravity_mm::phi, grids_gravity_mm::res_chi, grids_gravity_mm::res_phi, residual_mm(), restrict_grid(), grids_gravity_mm::source_chi, grids_gravity_mm::source_phi, grids_gravity_mm::temp_chi, and grids_gravity_mm::temp_phi.
Referenced by do_one_v_cycle().
go_down_mm()
void go_down_mm (struct grids_gravity_mm * gg, double a)
Moves everything to the next finer grid
Comments:
gg->g is the coarse.
gg->g-1 fine
References grids_gravity_mm::chi, grids_gravity_mm::g, grids_gravity_mm::h, grids_gravity_mm::n, grids_gravity_mm::par, grids_gravity_mm::phi, prolonge(), restrict_grid(), grids_gravity_mm::temp_chi, and grids_gravity_mm::temp_phi.
Referenced by do_one_v_cycle().