Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/gs_residual_truncation_error_mm.h File Reference
gs_residual_truncation_error_mm.h File Reference
Functions
void gs_mm (struct grids_gravity_mm *gg)
void residual_mm (struct grids_gravity_mm *gg, int grid, double ***res_phi, double ***res_chi)
void trunc_err_mm (struct grids_gravity_mm *gg, int grid, double ***trunc_phi, double ***trunc_chi)
Function Documentation
gs_mm()
void gs_mm (struct grids_gravity_mm * gg)
References grids_gravity_mm::a2M2, grids_gravity_mm::aa0, grids_gravity_mm::chi, grids_gravity_mm::cte_poisson_over_a, grids_gravity_mm::g, gs_node_mm(), grids_gravity_mm::h, grids_gravity_mm::n, grids_gravity_mm::phi, grids_gravity_mm::rho, grids_gravity_mm::source_chi, grids_gravity_mm::source_phi, sx_first_mm, sy_first_mm, and sz_first_mm.
Referenced by do_one_v_cycle().
residual_mm()
void residual_mm (struct grids_gravity_mm * gg, int grid, double *** res_phi, double *** res_chi)
Calculates residual on the grid "grid". Comments:
Note that the grid does not have to necessarily be the grid gg->g.
We do not store the result by default in the correponding variables in gg (instead we store it in the arguments res_phi, res_chi). This is in case you wat to store it somewhere else.
References grids_gravity_mm::a2M2, grids_gravity_mm::aa0, grids_gravity_mm::chi, grids_gravity_mm::cte_poisson_over_a, grids_gravity_mm::h, L_mm(), grids_gravity_mm::n, grids_gravity_mm::phi, grids_gravity_mm::rho, grids_gravity_mm::source_chi, and grids_gravity_mm::source_phi.
Referenced by cycle_v_mm(), go_up_mm(), and verbose_fine().
trunc_err_mm()
void trunc_err_mm (struct grids_gravity_mm * gg, int grid, double *** trunc_phi, double *** trunc_chi)
Estimates truncation error (i.e. error associated to the discretizatio of the differential equation).
Comments:
Note that the grid does not have to necessarily be the grid gg->g.
The estimator is: tau = P[ D(R(phi)) - R(D(phi)) ]
References grids_gravity_mm::a2M2, grids_gravity_mm::aa0, grids_gravity_mm::chi, grids_gravity_mm::fourh, grids_gravity_mm::h, L_mm(), grids_gravity_mm::n, grids_gravity_mm::phi, prolonge(), restrict_grid(), grids_gravity_mm::temp2_chi, grids_gravity_mm::temp2_phi, grids_gravity_mm::temp_chi, grids_gravity_mm::temp_phi, grids_gravity_mm::trunc_chi, and grids_gravity_mm::trunc_phi.
Referenced by cycle_v_mm().