Solve-MOND-MM: /home/claudio/GitHub/Solve/source/grid/init_grid.h File Reference
init_grid.h File Reference
Data Structures
struct grids
Functions
void init_grid (struct params *par, struct grids *grid)
Function Documentation
init_grid()
void init_grid (struct params * par, struct grids * grid)
References alloc_double_3(), grids::chi_bar_mm, grids::delta, grids::force_1, grids::force_2, grids::force_3, grids::force_chi_bar_mm_1, grids::force_chi_bar_mm_2, grids::force_chi_bar_mm_3, grids::force_phi_bar_mm_1, grids::force_phi_bar_mm_2, grids::force_phi_bar_mm_3, params::grid, init_fftw(), grids::phi, grids::phi_bar_mm, and grids::source.
Referenced by main().