Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/read_params.c File Reference
read_params.c File Reference
Reads the parameters file which is assumed to be called run.input.
Functions
void init_keywords (struct params *par, char keywords[50][1000], void *values[50], char type[50][10], int *found)
void check_keyword (char keywords[50][1000], void *values[50], char type[50][10], int *found, char *key, char *val)
void delete_spaces (char *str)
void read_params (struct params *par)
Detailed Description
Reads the parameters file which is assumed to be called run.input.
Function Documentation
init_keywords()
void init_keywords (struct params * par, char keywords[50][1000], void * values[50], char type[50][10], int * found)
References params::box, params::file_in_parts, params::file_out, params::gravity, params::grid, params::grid_p, params::hsmall, params::mm_a0, params::mm_KB, params::mm_M, params::n_outputs, params::nsteps, params::nthreads, params::omegal, params::omegam, params::static_test, params::verbose, params::verbose_mm, params::verbose_mm_coarse, params::z_end, and params::z_init.
Referenced by read_params().
check_keyword()
void check_keyword (char keywords[50][1000], void * values[50], char type[50][10], int * found, char * key, char * val)
Referenced by read_params().
delete_spaces()
void delete_spaces (char * str)
Referenced by read_params().
read_params()
void read_params (struct params * par)
References check_keyword(), delete_spaces(), fopen_check(), and init_keywords().
Referenced by main().