Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/read_params.h File Reference
read_params.h File Reference
Functions
void read_params (struct params *par)
Function Documentation
read_params()
void read_params (struct params * par)
References check_keyword(), delete_spaces(), fopen_check(), and init_keywords().
Referenced by main().