Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/releaser.h File Reference
releaser.h File Reference
Functions
void free_int_2 (int **a)
void free_int_3 (int ***a)
void free_int_4 (int ****a)
void free_float_2 (float **a)
void free_float_3 (float ***a)
void free_float_4 (float ****a)
void free_double_2 (double **a)
void free_double_3 (double ***a)
void free_double_4 (double ****a)
void free_long_2 (long **a)
void free_long_3 (long ***a)
void free_long_4 (long ****a)
void free_char_2 (char **a)
void free_char_3 (char ***a)
void free_char_4 (char ****a)
Function Documentation
free_int_2()
void free_int_2 (int ** a)
free_int_3()
void free_int_3 (int *** a)
free_int_4()
void free_int_4 (int **** a)
free_float_2()
void free_float_2 (float ** a)
free_float_3()
void free_float_3 (float *** a)
free_float_4()
void free_float_4 (float **** a)
free_double_2()
void free_double_2 (double ** a)
free_double_3()
void free_double_3 (double *** a)
Referenced by clean_up_grid(), deallocate_grids_mm(), solve_poisson_fftw(), and solve_spherical_mond().
free_double_4()
void free_double_4 (double **** a)
free_long_2()
void free_long_2 (long ** a)
free_long_3()
void free_long_3 (long *** a)
free_long_4()
void free_long_4 (long **** a)
free_char_2()
void free_char_2 (char ** a)
free_char_3()
void free_char_3 (char *** a)
free_char_4()
void free_char_4 (char **** a)