Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/commons_multigrid/restrict.c File Reference
restrict.c File Reference
Functions
void restrict_grid_cospatial (double ***old, double ***new, long n_old)
void restrict_grid_original (double ***old, double ***new, long n_old)
void restrict_grid (double ***old, double ***new, long n_old)
Function Documentation
restrict_grid_cospatial()
void restrict_grid_cospatial (double *** old, double *** new, long n_old)
Restriction routines which interpolate a field from a fina grid to a coarse grid (with half the number of points per dimension).
Comments:
See Trottenberg, Oosterlee, Schuller, "Multigrid" for details.
These routines are needed by the multigrid solver to move between grids.
There are several routines that use different interpolation order. Higher order is not necessarily better.
The only public routine is restrict_grid. The other routines are accessed through it. Uncomment the call you want to use.
restrict_grid_original()
void restrict_grid_original (double *** old, double *** new, long n_old)
Referenced by restrict_grid().
restrict_grid()
void restrict_grid (double *** old, double *** new, long n_old)
References restrict_grid_original().
Referenced by go_down_mm(), go_up_mm(), and trunc_err_mm().