Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/solve_multigrid_mm.h File Reference
solve_multigrid_mm.h File Reference
Data Structures
struct grids_gravity_mm
Macros
#define MAX_GRIDS 20
#define X 0
#define Y 1
#define Z 2
#define MINUS 0
#define PLUS 1
#define NGS 2
#define MAX_ITERATION 200
#define GO_UP_FIRST 1
#define GO_UP_SECOND 1
Functions
int solve_multigrid_mm (struct params *par, double ***dens, double ***chi, double ***phi, double box, double grid, double a)
Macro Definition Documentation
MAX_GRIDS
#define MAX_GRIDS 20
Number of pointers to grids (not necessarily allocated). (i.e. not important unless you want to have more than 20 levels).
X
#define X 0
For evaluating the MOND operator.
Y
#define Y 1
For evaluating the MOND operator.
Z
#define Z 2
For evaluating the MOND operator.
MINUS
#define MINUS 0
For evaluating the MOND operator.
PLUS
#define PLUS 1
For evaluating the MOND operator.
NGS
#define NGS 2
Number of Gauss-Seidel iterations per level.
MAX_ITERATION
#define MAX_ITERATION 200
Maximun number of complete V cycles before accepting that the solver will not converge.
GO_UP_FIRST
#define GO_UP_FIRST 1
default=1. If 0 then solver does not go up in the first multigrid level (i.e. one grid scheme).
GO_UP_SECOND
#define GO_UP_SECOND 1
default=1. If 0 then solver does not go up in the second multigrid level (i.e. two grids scheme).
Function Documentation
solve_multigrid_mm()
int solve_multigrid_mm (struct params * par, double *** dens, double *** phi, double *** chi, double box, double grid, double a)
Main routine of the multigrid solver for MOND-MM potentials
References grids_gravity_mm::a2M2, grids_gravity_mm::aa0, allocate_grids_mm(), grids_gravity_mm::chi, params::cte_poisson, grids_gravity_mm::cte_poisson_over_a, cycle_v_mm(), deallocate_grids_mm(), grids_gravity_mm::g, params::grid, grids_gravity_mm::KB, params::mm_a0, params::mm_KB, params::mm_M, grids_gravity_mm::num_grids, grids_gravity_mm::par, grids_gravity_mm::phi, pow2, grids_gravity_mm::verbose, grids_gravity_mm::verbose_coarse, params::verbose_mm, and params::verbose_mm_coarse.
Referenced by get_gravity(), and static_test().