Solve-MOND-MM: /home/claudio/GitHub/Solve/source/solve.c File Reference
solve.c File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Main routine. It initializes everything (physics, fine grid and particles) and gives control to the routine that does the time evolution.
References clean_up_grid(), init_grid(), init_parts(), init_physics(), leap_frog_variable(), read_params(), params::static_test, and static_test().