Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/newton/fft_solver/solve_poisson_fftw.h File Reference
solve_poisson_fftw.h File Reference
Functions
int solve_poisson_fftw (struct params *par, struct grids *grid, struct units *unit)
void transforms (double ***gr, double ***gi, double box, int grid, fftw_complex *data, fftw_plan p_backward)
void anti_transforms (double ***gr, double ***gi, double box, int grid, fftw_complex *data, fftw_plan p_forward)
Function Documentation
solve_poisson_fftw()
int solve_poisson_fftw (struct params * par, struct grids * grid, struct units * unit)
References alloc_double_3(), anti_transforms(), params::box, grids::data, free_double_3(), params::grid, grids::p_backward, grids::p_forward, grids::phi, pow2, grids::source, transforms(), and units::twopi.
Referenced by get_gravity(), solve_spherical_mond(), and static_test().
transforms()
void transforms (double *** gr, double *** gi, double box, int grid, fftw_complex * data, fftw_plan p_backward)
References index.
Referenced by solve_poisson_fftw().
anti_transforms()
void anti_transforms (double *** gr, double *** gi, double box, int grid, fftw_complex * data, fftw_plan p_forward)
References index, and pow3.
Referenced by solve_poisson_fftw().