Solve-MOND-MM: /home/claudio/GitHub/Solve/source/gravity/mond_mass/solve_spherical_mond.c File Reference
solve_spherical_mond.c File Reference
Macros
#define pow2(x) ((x)*(x))
#define pow3(x) ((x)*(x)*(x))
#define pow4(x) ((x)*(x)*(x)*(x))
#define pow5(x) ((x)*(x)*(x)*(x)*(x))
#define pow6(x) ((x)*(x)*(x)*(x)*(x)*(x))
Functions
int solve_spherical_mond (double ***phi, double a, fftw_complex *data, fftw_plan p_forward, fftw_plan p_backward, double power_a0)
Macro Definition Documentation
pow2
#define pow2 (x) ((x)*(x))
pow3
#define pow3 (x) ((x)*(x)*(x))
pow4
#define pow4 (x) ((x)*(x)*(x)*(x))
pow5
#define pow5 (x) ((x)*(x)*(x)*(x)*(x))
pow6
#define pow6 (x) ((x)*(x)*(x)*(x)*(x)*(x))
Function Documentation
solve_spherical_mond()
int solve_spherical_mond (double *** phi, double a, fftw_complex * data, fftw_plan p_forward, fftw_plan p_backward, double power_a0)
References alloc_double_3(), free_double_3(), and solve_poisson_fftw().