Solve-MOND-MM: /home/claudio/GitHub/Solve/source/tests/static_test.c File Reference
static_test.c File Reference
Functions
void static_test (struct params *par, struct grids *grid, struct particles *part, struct units *unit)
Function Documentation
static_test()
void static_test (struct params * par, struct grids * grid, struct particles * part, struct units * unit)
This is a static test. If the corresponding flag is on in the parameter file, then the code will read initial conditions, calculate all the relevant fields, write them in a file and stops execution. Comments:
There is a comparison between solutions obtained here and analytic solutions in the directory tests.
References params::a, params::box, calc_delta_cic(), calc_newt_source(), grids::chi_bar_mm, grids::delta, dist(), params::file_out, grids::force_1, grids::force_2, grids::force_3, grids::force_chi_bar_mm_1, grids::force_chi_bar_mm_2, grids::force_chi_bar_mm_3, grids::force_phi_bar_mm_1, grids::force_phi_bar_mm_2, grids::force_phi_bar_mm_3, forces(), params::grid, initial_guess_mm(), grids::phi, grids::phi_bar_mm, particles::pos_1, particles::pos_2, particles::pos_3, solve_multigrid_mm(), solve_poisson_fftw(), and params::z_init.
Referenced by main().