Solve-MOND-MM: /home/claudio/GitHub/Solve/source/time_evolution/time_evolution_standard_variable.h File Reference
time_evolution_standard_variable.h File Reference
Functions
void leap_frog_variable (struct params *par, struct grids *grid, struct particles *part, struct units *unit)
Function Documentation
leap_frog_variable()
void leap_frog_variable (struct params * par, struct grids * grid, struct particles * part, struct units * unit)
Here is the main time loop.
References a_of_t(), params::box, grids::force_1, grids::force_2, grids::force_3, get_gravity(), integrate_time_of_a(), interp_force_cic(), modulus(), params::nparts, params::nsteps, particles::pos_1, particles::pos_2, particles::pos_3, particles::vel_1, particles::vel_2, particles::vel_3, params::verbose, write_particles(), write_phi(), params::z_end, and params::z_init.
Referenced by main().