Solve-MOND-MM: /home/claudio/GitHub/Solve/source/libs/utils.c File Reference
utils.c File Reference
Functions
double modulus (double x, double y)
FILE * fopen_check (char *file, char *type)
double euclides2 (double x, double y, double z)
double euclides (double x, double y, double z)
double dist (double x, double y, double z)
void change_system (double vec[3][3], double *x, double *y, double *z)
void sort_3_values (double *a)
void index_1d_to_3d (double q, int *i, int *j, int *k, int n)
Function Documentation
modulus()
double modulus (double x, double y)
Referenced by leap_frog_variable(), and read_particles().
fopen_check()
FILE * fopen_check (char * file, char * type)
Referenced by read_params().
euclides2()
double euclides2 (double x, double y, double z)
References pow2.
euclides()
double euclides (double x, double y, double z)
References pow2.
dist()
double dist (double x, double y, double z)
References pow2.
Referenced by gs_node_mm(), L_mm(), and static_test().
change_system()
void change_system (double vec[3][3], double * x, double * y, double * z)
sort_3_values()
void sort_3_values (double * a)
index_1d_to_3d()
void index_1d_to_3d (double q, int * i, int * j, int * k, int n)
References pow2.